# Default values for Percona XtraDB Cluster

## percona image and version
## ref: https://hub.docker.com/r/percona/percona-xtradb-cluster/tags/
image:
  repository: "percona/percona-xtradb-cluster"
  tag: "5.7.19"
  pullPolicy: IfNotPresent

# Desired number of members of xtradb cluster
replicas: 3

## Specify password for root user
## If commented out will set a random password which may break upgrades
##
# mysqlRootPassword: not-a-secure-password

## Specify password for xtradb backup user
## If commented out will set a random password which may break upgrades
##
# xtraBackupPassword: replicate-my-data

## Uncomment to create a database user
##
# mysqlUser: test
# mysqlPassword: test

## Allow unauthenticated access, uncomment to enable
##
# mysqlAllowEmptyPassword: true

## Uncomment to Create a database
##
# mysqlDatabase: test

## Persist data to a persitent volume
persistence:
  enabled: false
  ## percona data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m

## Custom percona config files will be placed in /etc/mysql/conf.d
## default node.cnf is found in files/node.cnf and will be used if
## a custom node.cnf is not specified.
#
# configFiles:
#  node.cnf: |+
#    [mysqld]
#    datadir=/var/lib/mysql
#    default_storage_engine=InnoDB
#  foo.cnf: |+
#    ...
#    ...

## When set to true will create sidecar for `prom/mysqld-exporter`
#
metricsExporter: false

## When set to true will create sidecar to tail mysql log
#
logTail: true
